config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  # 記事の投稿、いいね、コメント
  resources :runs, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :likes, only: [:create, :destroy]
    resources :run_comments, only: [:create, :destroy]
  end

  # ユーザー情報
  resources :users, only: [:index, :show, :edit, :update] do
    get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw'
    put '/users/:id/withdraw' => 'users#withdraw'              
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  #タグ付け
  resources :tags do
    get 'runs', to: 'runs#search'
  end

  # 検索機能
  get '/search', to: 'search#search'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user                                  # 1つのuserに関連
  belongs_to :run                                   # 1つのrunに関連
  validates_uniqueness_of :run_id, scope: :user_id # 重複してしないこと
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @run = Run.find(params[:run_id])
    like = @run.likes.new(user_id: current_user.id)
    like.save
    redirect_to request.referer
  end

  def destroy
    @run = Run.find(params[:run_id])
    like = @run.likes.find_by(user_id: current_user.id)
    like.destroy
    redirect_to request.referer
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like-btn.html.erb
<% if user_signed_in? %>
<% if run.liked_by?(current_user) %>
  <%= link_to run.likes.count, run_likes_path(run), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to run.likes.count, run_likes_path(run), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
<% end %>
<% end %>

app/views/likes/create.js.erb
$("#run_<%= @run.id %> .like-btn").html("<%= j(render 'likes/like-btn', run: @run) %>");

app/views/likes/destory.js.erb
$("#run_<%= @run.id %> .like-btn").html("<%= j(render 'likes/like-btn', run: @run) %>");