config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  # 記事の投稿、いいね、コメント
  resources :runs, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :likes, only: [:create, :destroy]
    resources :run_comments, only: [:create, :destroy]
  end

  # ユーザー情報
  resources :users, only: [:index, :show, :edit, :update] do
    get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw'
    put '/users/:id/withdraw' => 'users#withdraw'              
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  #タグ付け
  resources :tags do
    get 'runs', to: 'runs#search'
  end

  # 検索機能
  get '/search', to: 'search#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :runs # 投稿記事と1対N
  has_many :likes, dependent: :destroy # いいねと1対N
  has_many :run_comments, dependent: :destroy # 投稿記事へのコメントと1対N
  attachment :profile_image, destroy: false
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # 自分がフォローされる（被フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # 自分がフォローする（与フォロー）側の関係性
  has_many :followers, through: :reverse_of_relationships, source: :follower # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followings, through: :relationships, source: :followed # 与フォロー関係を通じて参照→自分がフォローしている人

   #is_activeが無効だとログインできない
  def active_for_authentication?
    super && (self.is_active === true)
  end

  def liked_by?(run_id)
   likes.where(run_id: run_id).exists?
  end

  def follow(user_id) # フォローする
    relationships.create(followed_id: user_id) # createメソッドはnewとsaveを合わせた挙動
  end

  def unfollow(user_id) # フォロー外す
    relationships.find_by(followed_id: user_id).destroy # find_byによって1レコードを特定し、destroyメソッドで削除
  end

  def following?(user) # 引数に渡したユーザを、フォローしているかどうかを判定
    followings.include?(user) # include?で対象の配列に引数が含まれていればtrue、なければfalseを返す。
  end

  # 検索機能
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @runs = @user.runs
    @run = Run.new
    @runs = @runs.page(params[:page]).per(3)
  end

  def index
    @users = User.all
    @run = Run.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  #顧客退会画面
  def unsubscribe
    @user = User.find_by( params[:id])
  end

  #顧客退会処理
  def withdraw
    @user = User.find_by( params[:id])
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
    flash[:notice]='またのご利用お待ちしております。'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image,:is_active)
  end

  def check_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
  <div class="main_group">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.followings.count %></td>
            <td>フォロワー数: <%= user.followers.count %></td>
            <td>
              <% if current_user != user %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-info"  %>
                <% else %>
                  <%= link_to "フォロー", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
                <% end %>
              <% end %>
            </td>
            <td><%= link_to 'Show', user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user user_#{user.id}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/users/_info.html.erb
	<div class="main_group row">
		<table class="table table-hover">
			<thead>
				<div class="text-center col-6">
					<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg")  %>
				</div>
					<div class="text-center col-6">
						<% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
              <% else %>
                <%= link_to "フォロー", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
              <% end %>
            <% else %>
              <%= link_to '設定',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id} fa-2x" %>
            <% end %>
					</div>
			</thead>
			<tbody>
				<tr>
					<td class="text-center">名前</td>
					<td><%= user.name %></td>
					<td></td>
				</tr>
				<tr>
					<td class="text-center">自己紹介</td>
					<td><%= user.introduction %></td>
					<td></td>
				</tr>
				<tr>
					<td class="text-center">登録日</td>
					<td><%= user.created_at.strftime('%Y/%m/%d') %></td>
					<td></td>
				</tr>
				<tr>
					<td class="text-center">フォロー数</td>
					<td><%=  link_to user.followings.count, user_followings_path(user) %>人</td>
					<td></td>
				</tr>
				<tr>
					<td class="text-center">フォロワー数</td>
					<td><%= link_to user.followers.count, user_followers_path(user) %>人</td>
					<td></td>
				</tr>
			</tbody>
		</table>
	</div>

app/views/users/_run_index.html.erb
  <div class="main_group">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>タイトル</th>
          <th>本文</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <!--投稿内容一覧-->
      <tbody>
        <% runs.each do |run| %>
          <tr>
            <td><%= link_to user_path(run.user) do %>
              <%= attachment_image_tag(run.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
              <% end %>
            </td>
            <td><%= link_to run.title, run_path(run), class: "run_#{run.id}" %></td>
            <td><%= run.body %></td>
            <td id="likes_buttons_<%= run.id %>">
              <%= render partial: 'likes/like-btn', locals:{run: run} %>
            </td>
            <td>コメント数: <%= run.run_comments.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination">
      <%= paginate runs %></br>
    </div>
  </div>

  <h4>7日間分の投稿数</h4>
    <table class='table table-bordered'>
      <thead>
        <tr>
          <th>６日前</th>
          <th>５日前</th>
          <th>４日前</th>
          <th>３日前</th>
          <th>２日前</th>
          <th>１日前</th>
          <th>今日</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= runs.created_6day_ago.count %></td>
          <td><%= runs.created_5day_ago.count %></td>
          <td><%= runs.created_4day_ago.count %></td>
          <td><%= runs.created_3day_ago.count %></td>
          <td><%= runs.created_2day_ago.count %></td>
          <td><%= runs.created_yesterday.count %></td>
          <td><%= runs.created_today.count %></td>
        </tr>
      </tbody>
    </table>

    <canvas id="myLineChart"></canvas>
    <script>
      $(document).on('turbolinks:load', function() {
        var ctx = document.getElementById("myLineChart");
        var myLineChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [
              {
                label: '投稿数',
                data: [<%= runs.created_6day_ago.count %>,
                       <%= runs.created_5day_ago.count %>,
                       <%= runs.created_4day_ago.count %>,
                       <%= runs.created_3day_ago.count %>,
                       <%= runs.created_2day_ago.count %>,
                       <%= runs.created_yesterday.count %>,
                       <%= runs.created_today.count %>],
                borderColor: "rgba(0,0,255,1)",
                backgroundColor: "rgba(0,0,0,0)"
              }
            ],
          },
          options: {
            title: {
              display: true,
              text: '7日間の投稿数の比較'
            },
            scales: {
              yAxes: [{
                ticks: {
                  suggestedMax: 10,
                  suggestedMin: 0,
                  stepSize: 1,
                  callback: function(value, index, values){
                    return  value
                  }
                }
              }]
            },
          }
        });
      });
    </script>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    <th><%= link_to '退会する',user_unsubscribe_path(@user.id), class: 'btn btn-danger' %></th>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10 offset-md-1'>
      <h2>
        <i class="fas fa-users fa-lg"></i>ユーザー一覧
      </h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <div class='container '>
    <h2>
      <i class="fas fa-address-card fa-lg"></i>プロフィール
    </h2>
    <%= render 'info', user: @user %>
  </div>
  <div class='container '>
    <h2>
      <i class="fas fa-bookmark fa-lg"></i>投稿一覧
    </h2>
    <%= render 'run_index',runs: @runs %>
  </div>
  <div class='container '>
    <% if @user == current_user %>
      <h2 class="row-md-3">
        <i class="fas fa-folder-plus fa-lg"></i>新規投稿
      </h2>
      <%= render 'runs/form', run: @run %>
    <% end %>
  </div>

app/views/users/unsubscribe.html.erb
  <div class='container my-5'>
    <div class='row mb-3'>
      <div class='col-md-10 offset-md-1'>
        <h3 class='text-center'>本当に退会しますか？</h3>
        <div class='p-3 text-center'>
          <p>退会すると、会員登録情報や</p>
          <p>これまでの投稿記録、フォローが閲覧できなくなります。</p>
          <p>退会する場合は、「退会する」をクリックしてください。</p>
        </div>
        <div class='p-3 text-center'>
          <%= link_to '退会しない',edit_user_path(@user.id), class: 'btn btn-primary btn-lg' %>
          <%= link_to '退会する',user_withdraw_path(@user.id), method: :patch, class: 'btn btn-danger', 'data-confirm' => '本当によろしいですか？' %>
        </div>
      </div>
    </div>
  </div>