config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  # 記事の投稿、いいね、コメント
  resources :runs, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :likes, only: [:create, :destroy]
    resources :run_comments, only: [:create, :destroy]
  end

  # ユーザー情報
  resources :users, only: [:index, :show, :edit, :update] do
    get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw'
    put '/users/:id/withdraw' => 'users#withdraw'              
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  #タグ付け
  resources :tags do
    get 'runs', to: 'runs#search'
  end

  # 検索機能
  get '/search', to: 'search#search'
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :run_comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  attachment :image
 

  # 引数で渡されたユーザidがLikeテーブル内に存在（exists?）するかの判断
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

# タグ付け
  def save_tag(sent_tags)
  end

#投稿数
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) } # 2日前
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) } # 3日前
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) } # 4日前
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) } # 5日前
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) } # 6日前

  # 検索機能
  def self.search_for(content, method)
    if method == 'perfect'
      Run.where(title: content)
    elsif method == 'forward'
      Run.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Run.where('title LIKE ?', '%' + content)
    else
      Run.where('title LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_correct_user, only: [:edit, :update, :destroy]

  def show
    @run = Run.find(params[:id])
    @run_comment = RunComment.new
    @run_tags = @run.tags
  end

  def index
    runs = Run.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    @runs = Kaminari.paginate_array(runs).page(params[:page]).per(10)
    @run = Run.new
    @tag_list = Tag.all
  end

  def create
    @run = Run.new(run_params)
    @run.user_id = current_user.id
    tag_list = params[:run]
    if @run.save
       @run.save_tag(tag_list)
       redirect_to run_path(@run), notice: "You have created run recode successfully."
    else
      @runs = Run.all
      render 'index'
    end
  end



  def edit
    @run =Run.find(params[:id])
  end

  def update
    @run =Run.find(params[:id])
    tag_list = params[:run]
    if @run.update(run_params)
       @run.save_tag(tag_list)
       redirect_to run_path(@run), notice: "You have updated run recode successfully."
    else
      render "edit"
    end
  end

  def destroy
    @run.destroy
    redirect_to runs_path
  end

  def search
    @tag_list = Tag.all  #こっちの投稿一覧表示ページでも全てのタグを表示するために、タグを全取得
    @tag = Tag.find(params[:tag_id])  #クリックしたタグを取得
    @runs = @tag.runs.all           #クリックしたタグに紐付けられた投稿を全て表示
  end

  private
  def run_params
    params.require(:run).permit(:title, :body,:image, tag_ids: [])
  end

  def check_correct_user
    @run = Run.find(params[:id])
    unless @run.user == current_user
      redirect_to runs_path
    end
  end
end

app/helpers/run_helper.rb
module RunHelper
end

app/views/runs/_comment.html.erb
<h2>コメント欄</h2>
  <table>
    <tr>
      <td>
        <%= form_with model:[@run,@run_comment], local: true do |f| %>
         <%= f.text_area :comment  %><br>
         <div id="evaluate_stars">
           <label>評価</label>
         </div>
         <div class="actions">
          <%= f.submit '送信'%>
         </div>
        <% end %>
      </td>
    </tr>
    <% @run.run_comments.each do |run_comment| %>
      <% run_comment_user = run_comment.user %>
      <tr>
        <td>
          <%= link_to user_path(run_comment_user), class: "user_#{run_comment_user.id}" do %>
          <%= attachment_image_tag run_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
          <%= run_comment_user.name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <%= run_comment.comment %>
        </td>
      </tr>
      <tr>
        <td class="run_comments-evaluation" data-score="<%= run_comment.evaluation %>">
        </td>
       <% if current_user == run_comment_user %>
        <td>
          <%= link_to 'Destroy', run_run_comment_path(run_comment.run_id,run_comment.id), class: 'btn-sm btn-danger', method: :delete %>
        </td>
       <% end %>
      </tr>
    <% end %>
  </table>

<script>
  $(function(){

    $('#evaluate_stars').raty({
      size: 36,
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      scoreName: 'run_comment[evaluation]' //登録するモデル名とカラム名を記述
    });
    $('.run_comments-evaluation').raty({
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      },
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
    });
  });
</script>

app/views/runs/_form.html.erb
  <div class="main_group">
    <%= form_with model:run,local:true do |f| %>
      <div class="form-group">
        <%= f.label :タイトル %>
        <%= f.text_field :title, class: 'form-control run_title' %>
      </div>
      <div class="form-group">
        <%= f.label :本文 %>
        <%= f.text_area :body, class: 'form-control run_body' %>
      </div>
      <div class="form-group">
        <h4>画像</h4>
        <%= f.attachment_field :image %>
      </div>
      <div class="field">
        <%= f.label :tag_ids, 'タグ付' %>
        <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :tag_name do |b| %>
        <%= b.check_box + b.label %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>

app/views/runs/_index.html.erb
  <div class="ranking-group">
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>タイトル</th>
          <th>いいね数</th>
          <th>コメント</th>
        </tr>
      </thead>
      <!--投稿内容一覧-->
     <tbody>
        <% runs.each do |run| %>
          <tr>
            <td><%= link_to user_path(run.user) do %>
              <%= attachment_image_tag(run.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
              <% end %>
            </td>
            <td><%= link_to run.title, run_path(run), class: "run_#{run.id}" %></td>
            <td id="likes_buttons_<%= run.id %>">
              <%= render partial: "likes/like-btn", locals:{run: run} %>
            </td>
            <td>コメント数: <%= run.run_comments.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/runs/edit.html.erb
  <div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Run</h1>
        <%= render 'layouts/errors', obj: @run %> <!--obj:オブジェクト-->
        <%= render 'form', run: @run %>
        <%= link_to 'Show', run_path(@run), class: "run_#{@run.id}" %> |
        <%= link_to 'Back', runs_path, class: "back" %>
      </div>
    </div>
  </div>

app/views/runs/index.html.erb
  <div class='container px-5 px-sm-0'>
    <%= render 'layouts/errors', obj: @run %>
    <div class='row'>
      <div class='col-md-3 '>
        <h2><i class="fas fa-tag"></i> タグリスト</h2>
         <%= render 'tags/index', tags: @tag_list %>
      </div>
      <div class='text-center col-md-9 '>
        <h2>ランニング記事一覧</h2>
        <h4 >
          <i class="fas fa-crown "></i> いいねランキング
        </h4>
        <%= render 'index', runs: @runs%>
      </div>
    </div>
  </div>

app/views/runs/search.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>本文</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <!--投稿内容一覧-->
  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= link_to user_path(run.user) do %>
          <%= attachment_image_tag(run.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to run.title, run_path(run), class: "run_#{run.id}" %></td>
        <td><%= run.body %></td>
        <td id="likes_buttons_<%= run.id %>">
          <%= render partial: 'likes/like-btn', locals:{run: run} %>
        </td>
        <td>コメント数: <%= run.run_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/runs/show.html.erb
  <div class='container '>
    <div class='row'>
      <div class='col-md-3'>
        <%= render 'runs/comment', run: @run,run_comment: @run_comment%>
      </div>
      <div class='col-md-9'>
        <h2>詳細ページ</h2>
        <table class='table'>
          <tr>
            <td><%= link_to user_path(@run.user) do %>
              <%= attachment_image_tag(@run.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
              <%= @run.user.name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to @run.title, run_path(@run) %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @run.body %>
            </td>
          </tr>
          <tr>
            <td>
              <h2>画像</h2>
              <%= attachment_image_tag @run, :image, :fill, 300, 300, format: 'jpg' %>
            </td>
            <% @run_tags.each do |tag| %>
              <tr>
                <td>
                  <span class="tag">
                    <%= link_to tag.tag_name,tag_runs_path(tag_id: tag.id) %>
                  </span>
                </td>
              </tr>
            <% end %>
          </tr>
          <tr>
            <td class="favorite-btn">
              <%= render "likes/like-btn", run: @run %>
            </td>
          </tr>
          <tr>
            <td>
              コメント数: <%= @run.run_comments.count %>
            </td>
          </tr>
          <% if @run.user == current_user %>
            <tr>
              <td>
                <%= link_to 'Edit', edit_run_path(@run), class: "btn btn-sm btn-success edit_run_#{@run.id}" %>
                <%= link_to 'Destroy', run_path(@run), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_run_#{@run.id}"%>
              </td>
            </tr>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>


  <script>
    
  </script>