config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  # 記事の投稿、いいね、コメント
  resources :runs, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :likes, only: [:create, :destroy]
    resources :run_comments, only: [:create, :destroy]
  end

  # ユーザー情報
  resources :users, only: [:index, :show, :edit, :update] do
    get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw'
    put '/users/:id/withdraw' => 'users#withdraw'              
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  #タグ付け
  resources :tags do
    get 'runs', to: 'runs#search'
  end

  # 検索機能
  get '/search', to: 'search#search'
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <div class='bg-dark text-white'>
    <div class='container'>
      <div class='row'>
        <div class='mx-auto text-center'>
          <p>Copyright © 2021 Runformation All Rights Reserved.</p>
        </div>
        <div class='mx-auto text-right'>
          <ul class='navbar-nav ml-auto'>
            <% if user_signed_in? %>
              <li><%= link_to ' Mypageへ',user_path(current_user),class: 'fas fa-home nav-link text-light' %></li>
            <% else %>
              <li><%= link_to "Topへ", root_path,class:"fas fa-home nav-link text-light" %></li>
            <% end %>
         </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_header.html.erb
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>   <i class="fas fa-running fa-lg"></i>Runformation</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li><%= link_to ' Mypage',user_path(current_user),class: 'fas fa-home nav-link text-light ' %></li>
            <li><%= link_to ' About',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
            <li><%= link_to ' Users',users_path,class: 'fas fa-users nav-link text-light' %></li>
            <li><%= link_to ' Runs',runs_path ,class: 'fas fa-running nav-link text-light' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
          <% else %>
            <li><%= link_to ' Home',root_path,class: 'fas fa-home nav-link text-light' %></li>
            <li><%= link_to ' About',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
            <li><%= link_to ' sign up', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
            <li><%= link_to ' login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

app/views/layouts/_search.html.erb
 <!--検索窓-->
  <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Run" => "run" }) %>
      <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }) %>
      <%= submit_tag '検索' %>
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Runformation</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
       <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
       <%= favicon_link_tag('favicon.ico') %>
    </head>
    <body>
      <%= render 'layouts/header' %>
      <main>
        <% if user_signed_in? %>
          <%= render 'layouts/search' %>
        <% end %>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
      <%= render 'layouts/footer' %>
    </body>
  </html>